/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct SDL_Rect {
    int x;
    int y;
    int w;
    int h;
};

struct SDL_VideoData;

struct SDL_Window;

struct SDL_WindowData {
    struct SDL_Window *_field1;
    id _field2;
    int _field3;
    id _field4;
    struct SDL_VideoData *_field5;
};

struct _NSPoint {
    float _field1;
    float _field2;
};

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSRect {
    struct _NSPoint _field1;
    struct _NSSize _field2;
};

struct _NSSize {
    float _field1;
    float _field2;
};

