/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface SDLAppDelegate : NSObject
{
}

- (BOOL)application:(id)arg1 openFile:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (unsigned int)applicationShouldTerminate:(id)arg1;

@end

