/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

#import "NSTextInput-Protocol.h"

@class NSString;

@interface SDLTranslatorResponder : NSView <NSTextInput>
{
    NSString *_markedText;
    struct _NSRange _markedRange;
    struct _NSRange _selectedRange;
    struct SDL_Rect _inputRect;
}

- (id)validAttributesForMarkedText;
- (unsigned int)characterIndexForPoint:(struct _NSPoint)arg1;
- (int)conversationIdentifier;
- (id)attributedSubstringFromRange:(struct _NSRange)arg1;
- (struct _NSRect)firstRectForCharacterRange:(struct _NSRange)arg1;
- (void)unmarkText;
- (void)setMarkedText:(id)arg1 selectedRange:(struct _NSRange)arg2;
- (struct _NSRange)selectedRange;
- (struct _NSRange)markedRange;
- (BOOL)hasMarkedText;
- (void)doCommandBySelector:(SEL)arg1;
- (void)insertText:(id)arg1;
- (void)setInputRect:(struct SDL_Rect *)arg1;

@end

